apiVersion: v1
kind: Service      # Create new service 
metadata:
  name: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  labels:
{{- include "spring.labels" . | nindent 4 }}
spec:
  selector:
{{- include "spring.labels" . | nindent 3 }}
  type: LoadBalancer
  ports:          # Map incoming port to target port
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080